apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-services
  labels:
    app: model
spec:
  replicas: 5
  selector:
    matchLabels:
      app: model-services
  template:
    metadata:
      labels:
        app: model-services
    spec:
      containers:
      - name: model-services
        image: model-services
        ports:
        - containerPort: 5672
        imagePullPolicy: IfNotPresent
        env:
          - name: MQ_HOST
            value: "rabbitmq-cluster"
          - name: MQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster-default-user
                key: username
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster-default-user
                key: password
          - name: FEATURE_STDS
            value: "[374.02855481460574, 11.102259862692481, 0.004641547155806401, 0.7245245578813498, 3.955913174878866]"
          - name: FEATURE_MEANS
            value: "[920.756442, 14.4969765, 0.00803971418, 3.23909807, 3.3909654]"